apiVersion: v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: ConfigMap
metadata:
  name: wp-config
  namespace: webs
data:
  WP_DB_HOST: mysql
  WP_DB_USER: mysql
  WP_DB_PASSWORD: mysql

